version: '3.9'

name: starter-pack

networks:
  server_network:

volumes:
  database_volume:

services:
  server:
    container_name: starter-pack_server
    build: .
    env_file: ./.env
    ports:
      - "3000:3000"
    networks:
      - server_network
    depends_on:
      - database

  database:
    container_name: starter-pack_database
    image: postgres:16.0-alpine3.18
    restart: always
    env_file: ./.env
    ports:
      - "5432:5432"
    volumes:
      - database_volume:/var/lib/postgresql/data
    networks:
      - server_network
